### ISSUE TITLE
Strip debug info from built binaries

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind-installer#24]
since moving to the new build all the binaries are now a couple MB bigger

from Liam:
> The build command should have this .. `-ldflags="-s -w"` in it to strip it

**Comment by tobespc** [comment]
@tetchel This is now done, please review and close if happy

**Comment by tetchel** [comment]
v'fied 
![image](https://user-images.githubusercontent.com/8888438/60049808-1c47a500-969d-11e9-8509-f9b342383317.png)
