### ISSUE TITLE
Windows runtime error occurred while trying to click on "Remove Codewind Images"

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind-installer#27]
**Environment:**
- **Codewind version:** Latest Development Version
- **VS Code version:** 1.35.1
- **OS:** VM with Windows 10

**Description:**
Windows runtime error occurred while trying to click on "Remove Codewind Images".
![image](https://user-images.githubusercontent.com/49531960/59947345-f58a3400-943a-11e9-989b-0cfe9ff5b047.png)

**Steps to reproduce the problem:**
1. Stop Codewind
2. Right click on "Remove Codewind Images"

**Log:**
[codewind-tools.log](https://github.com/eclipse/codewind-installer/files/3315826/codewind-tools.log)

@jagraj

**Comment by liamchampton** [comment]
@sujeilyfonseca Can you confirm if this is still happening with latest?

**Comment by sujeilyfonseca** [comment]
I reviewed this problem with the latest version, and it is not happening anymore. Therefore, I will proceed to close this issue.
