### ISSUE TITLE
Cannot stop codewind using latest installer on Windows

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind-installer#287]
### Description

If you have codewind up and running and run `./cwctl stop-all` it does not stop and take down PFE. Workaround is too manually take down PFE container but that is not user friendly.

**Comment by makandre** [comment]
Related to https://github.com/eclipse/codewind/issues/1478 perhaps?

**Comment by james-wallis** [comment]
Need more information.
* Can I have the logs for the failing `stop-all` command? 
* Version is latest master? (from your comment on the other issue)

**Comment by ssh24** [comment]
It was on PFE container.

Interestingly I just tried again right now and it worked. I think when I tried it this morning your change was not pushed to the image yet?

**Comment by james-wallis** [comment]
Ah ok, if you cannot reproduce can this issue be closed?

**Comment by ssh24** [comment]
Closing as this was probably fixed after the latest image being published with the change.
