### ISSUE TITLE
Remove image pulling from artifactory

### ISSUE THREAD

**Issue by liamchampton** [eclipse/codewind-installer#29]
**Subject of the issue**
With artifactory credentials set, the `install-dev` command will pull development images from artifactory. This needs to be removed.

Using plugin:
1) Set user auth credentials
2) Run codewind plugin
3) Images are downloaded from artifactory

Using installer:
1) Set user auth credentials
2) Run command `install-dev`
3) Images are downloaded from artifactory

**Expected behavior**
Should only pull images form dockerhub.

**Comment by tetchel** [comment]
Probably the `install` command should accept the tag to pull, defaulting to the latest prod release
