### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by liamchampton** [eclipse/codewind-installer#30]
**Subject of the issue**
Current readme has instructions to set env vars to pull from artifactory. Since artifcatory image pulling is being removed, the instructions needs to go too/changed to make sure the user is logged into docker instead.

**Comment by jgwest** [comment]
@liamchampton While you're at it, the README.md also contains references to internal `github.ibm.com` URLs. You can do a `grep -r -i "github.ibm.com" codewind-installer` for latest list.

**Comment by sishida** [comment]
@liamchampton Thanks for raising this issue. :) I'm going to try to create a PR for these edits. Could you please assign this issue to me? I am currently not a committer, so I can't assign myself. Thanks!

**Comment by sishida** [comment]
@liamchampton I made a pull request for these edits: https://github.com/eclipse/codewind-installer/pull/49 I imagine it's not wholly accurate, but hopefully we can use it to start discussion about the changes we need to make to the Readme. :)
