### ISSUE TITLE
Uninstall should work even if user containers are still running

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind-installer#33]
The uninstall fails when only a stop is done beforehand instead of a stop-all, but this should work.  User containers should not affect install or uninstall.

The error message is:

 REMOVE_IMAGE_ERROR[105]: exit status 1. Failed to remove image - Please make sure all containers are stopped

**Comment by tobespc** [comment]
So just to clarify, the use case is
1) developer installs codewind
2) developer create codewind project and starts it running
3) developer uninstalls codewind, but want there project to stay running ?

We have gone for the design that if you uninstall codewind, any build artifacts should also be removed.  What would be the value in leaving the container running after removing codewind ?

**Comment by eharris369** [comment]
What is the value of stopping Codewind and leaving the containers running?  When Codewind is restarted it rebuilds everything anyway?

**Comment by eharris369** [comment]
What was the original purpose of having both stop and stop-all commands?  If it is not useful to stop Codewind and leave the user containers running then that would simplify the code in the IDEs as they would not have to ask the user what they want to do.  If it is useful then it should work for uninstall too.

**Comment by liamchampton** [comment]
@eharris369 can this be closed?

**Comment by eharris369** [comment]
Sure.  I have just disabled the stop support in the IDE and only allow stop-all so now uninstall always works.
