### ISSUE TITLE
create 'latest' folder to store the latest build in download area

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind-installer#43]
For master branch build, it would be convenient if we copy and preserve the latest build in 'latest' directory in download area. i.e. _https://download.eclipse.org/codewind/codewind-installer/master/lastest_. Especially, it will help test automation and SVT. 
Currently, this has been done for plugins and vscode builds.

**Comment by tobespc** [comment]
Hi @josephca Can you provide some more info as to what this issue it for please and what it will solve ?  thanks

**Comment by josephca** [comment]
Hi @tobespc, sorry for the late response. I updated the summary accordingly.

**Comment by liamchampton** [comment]
@josephca Is this still relevant? If so, can this be moved to a codewind?(better visability). If not, can it be closed?

**Comment by tobespc** [comment]
Issue moved to [eclipse/codewind #1218](https://github.com/eclipse/codewind/issues/1218) via [**ZenHub**](https://www.zenhub.com/)
