### ISSUE TITLE
--tag/-t flag on remove command

### ISSUE THREAD

**Issue by liamchampton** [eclipse/codewind-installer#50]
**Subject of the issue**
The `install` and `start` command both have the option to specify an image tag. This should also be an option for the `remove` command.

**Expected behaviour**
Should the user have multiple codewind images on their machine, they should be able to specify which ones they want to remove.

**Comment by tetchel** [comment]
> Should the user have multiple codewind images on their machine, they should be able to specify which ones they want to remove.

This means the IDEs also need a way to ask the installer if the user has multiple image versions
