### ISSUE TITLE
Restrict PFE port range to avoid clashes with application port usage

### ISSUE THREAD

**Issue by mattcolegate** [eclipse/codewind-installer#69]
Auto-assigning ports for the PFE container has revealed a problem in the assigning of the port to be used.
As PFE specifies the hostname interface to be used as 127.0.0.1 (loopback or localhost) we just bind to the port on that interface (say, 32770).
When an application is created, this binds to all interfaces on the first available port, using the IP shorthand 0.0.0.0, This will bind to the public interfaces of any attached hardware, but is unable to bind on localhost because PFE got there first. The port was still marked as available because PFE asked for it just on localhost, not on 0.0.0.0.
We can't use 0.0.0.0 for PFE because that would then expose it on all interfaces, including public ones, creating a security omnishambles. Therefore in order to fix this without losing the dynamic port assignment, we will have PFE try to connect on a range of ports - 10000 to 11000 - that avoids the ranges assigned by Docker (32700+) whilst retaining the ability to skip over any ports that might be in use by other processes.

**Comment by liamchampton** [comment]
@mattcolegate this issue can be closed now
