### ISSUE TITLE
Cannot build the codewind installer- requires a later version of golang

### ISSUE THREAD

**Issue by ericdylanpeters2** [eclipse/codewind-installer#9]
This issue mirrors https://bugs.eclipse.org/bugs/show_bug.cgi?id=548352
As part of the installer build the installer for windows needs to be digitally signed otherwise the install of additional containers is blocked by most windows OS.

**Comment by tetchel** [comment]
this can be closed

**Comment by liamchampton** [comment]
@ericdylanpeters2

**Comment by ericdylanpeters2** [comment]
Fixed
